kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "gluster-block"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gb